// Code generated by MockGen. DO NOT EDIT.
// Source: double.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAction is a mock of Action interface
type MockAction struct {
	ctrl     *gomock.Controller
	recorder *MockActionMockRecorder
}

// MockActionMockRecorder is the mock recorder for MockAction
type MockActionMockRecorder struct {
	mock *MockAction
}

// NewMockAction creates a new mock instance
func NewMockAction(ctrl *gomock.Controller) *MockAction {
	mock := &MockAction{ctrl: ctrl}
	mock.recorder = &MockActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAction) EXPECT() *MockActionMockRecorder {
	return m.recorder
}

// Double mocks base method
func (m *MockAction) Double(i *int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Double", i)
	ret0, _ := ret[0].(error)
	return ret0
}

// Double indicates an expected call of Double
func (mr *MockActionMockRecorder) Double(i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Double", reflect.TypeOf((*MockAction)(nil).Double), i)
}
